"""replace color with size on products

Revision ID: 82b79ff1c654
Revises: b5771a9de2ae
Create Date: 2026-09-03 16:20:20.678322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '82b79ff1c654'
down_revision: Union[str, Sequence[str], None] = 'b5771a9de2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size', sa.String(length=50), nullable=True))
    op.drop_column('products', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('color', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('products', 'size')
    # ### end Alembic commands ###
